version: '3'
services:
  nginx:
    image: pranayraut11/nginx
    restart: always
    ports:
      - 8081:80
      
  app:
    container_name: app
    image: pranayraut11/samplejavawebsite
    ports:
      - 8080:8080  